### ISSUE TITLE
Mod Suggestions: Yung's better cave & mineshaft generation

### ISSUE THREAD

**Issue by bamvsgame** [ValhelsiaTeam/Valhelsia#102]
I think these mods would be a good fit for valhelsia, especially since they focus on world generation.

**Comment by Vaelzan** [comment]
I've been in contact with YUNG about fixing some small issues with his mods before we consider them (they can rarely cause crashes in big mod packs), but they're certainly ones we will consider in the future (no guarantees, just consideration) once the mods have been polished up a bit (since the Mineshaft one just came out).

**Comment by Khytwel** [comment]
YUNG's Better Mineshafts is now implemented to the latest version 2.2.5. For YUNG's Better Cave or similar mod we'll be waiting for Valhelsia 3.
