### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by carstorm** [ValhelsiaTeam/Valhelsia#111]
No crash report so heres the server log (to big to put on paste services so attached)
[2020-06-26-14.log](https://github.com/ValhelsiaTeam/Valhelsia/files/4838854/2020-06-26-14.log)

And [client log](https://pastebin.com/FCi9rVqF) if that helps

**Comment by Vaelzan** [comment]
Please use Discord to get support for crashes as per the readme (https://github.com/ValhelsiaTeam/Valhelsia/issues/5): https://discordapp.com/invite/reQZEXu

**Comment by carstorm** [comment]
Ahh i read that but don't see how this is different than #105 or #80 which both are also crashes and issues that happen in game. Anyways will move over to discord.

**Comment by Vaelzan** [comment]
Notice that in #105 I also told them to use Discord in future. I only answered it because I knew the answer immediately anyway. Crashes here are generally only for when I've asked people to create an issue after support has been attempted already, such as when we're waiting on a mod update, and that is so we can keep track.
