### ISSUE TITLE
[Mod Suggestion] ServerUtils

### ISSUE THREAD

**Issue by Elrol** [ValhelsiaTeam/Valhelsia#132]
Its a mod that adds lots of quality of life commands, similar to the Essentials plugin. Each command can be configured with different delays, cooldowns, aliasses, and permissions. 

Just a few of the more useful commands:

/home
/spawn
/back
/warp
/rtp

You can also setup ranks and permissions, including rank colors and prefix/suffix.
There are also 2 custom colorcodes (and it supports the minecraft colorcodes)

&g : makes the text rainbow, so you dont have to type each color code before the letter
&h : has stylized color schemes based on each month. (monthly colors can be changed in the config)

If you want to know more about it, check out the page here:
https://www.curseforge.com/minecraft/mc-mods/server-utilities

**Comment by Vaelzan** [comment]
It looks like a great mod, but we prefer to leave server-side mods up to server administrators so that they can customise things the way they want. The only ones that we would include in the pack are ones that need to be installed on the client side too.

The pack already has RTP in it (/mc rtp), and the other commands are similar in function to what the Waystones mod is for, so quite a few of the functions are redundant outside of the ones that a server administrator might use such as kits and ranks.
