### ISSUE TITLE
Can't create the Immersive Engineering core sample drill

### ISSUE THREAD

**Issue by mastrude** [ValhelsiaTeam/Valhelsia#135]
Can’t make the Immersive Engineering core sample drill because the IE steel fence is converted to the Mapper Base steel fence and then the recipe doesn’t recognize it.

**Comment by Vaelzan** [comment]
That's what the Polymorph mod was added for. It lets you choose between multiple outputs when the recipe is the same. The problem is it triggered a crash in the Placebo mod and so many people needed to remove it. The good news is that this crash was fixed yesterday so the next pack update will resolve it.

**Comment by ChloeDawn** [comment]
Polymorph does not appear to be working for this particular case.
Also, it would not resolve the problem the conflict causes for automation.

![Screenshot of crafting screen](https://user-images.githubusercontent.com/9869940/86535944-c6c2ec80-bedb-11ea-8cd3-e3fb0decf255.png)

**Comment by Vaelzan** [comment]
Polymorph is gradually adding support for additional various methods of crafting. They recently added support for Simple Storage Network, for example, as well as Silent Gear's crafting station. It is likely that with time it will support automation via things like Refined Storage as well, but given that very few people are going to need to automate steel fence production it isn't a high priority change on our side.
