### ISSUE TITLE
Server crashing, game crashing

### ISSUE THREAD

**Issue by MachoCrotcho** [ValhelsiaTeam/Valhelsia#199]
Parts of mekanism aren’t working. None of immersive engineer is working. Unplayable.

**Comment by MachoCrotcho** [comment]
Uh, just close it without addressing what I said? Makes sense. Thanks forge the support

**Comment by kevin4998** [comment]
@MachoCrotcho There is a [README issue](https://github.com/ValhelsiaTeam/Valhelsia/issues/5) explanation about how to set up such requests. There is a specific line which says

"Moreover, if you open an issue and you don't give us the logs or crash-reports, it will be directly dismissed!"

which appears to be the case here. They don't just randomly dismiss it but ignore ones which don't follow the README because of the large number of issues they get. I expect the team to care about the modpack and its users.

(From: Another Valhelsia user)

**Comment by MachoCrotcho** [comment]
Well now I feel like a dick. Had no idea, thanks for the info kind sir.
