### ISSUE TITLE
My other thread was closed, but there IS NO CRASH REPORT

### ISSUE THREAD

**Issue by TheBigTater** [ValhelsiaTeam/Valhelsia#229]
How am I supposed to leave a crash report when there is none. Twitch can't find one, I can't find one, nothing. It just crashes on startup for no reason before the game can even start loading. I would appreciate at least some help..

**Comment by kevin4998** [comment]
@TheBigTater There is a [README issue](https://github.com/ValhelsiaTeam/Valhelsia/issues/5) explaining how to setup such requests. In this issue there is a specific line which says:

"For any help request about a client crash directly after launching or the installation of the modpack/launcher this happens at the Discord server support level (There is a FAQ channel there that will help you with that problem)."

which I think is relevant here. They don't just randomly dismiss it but ignore ones which don't follow the README because of the large number of issues they get. I expect the team to care about the modpack and its users which is why they talk to and help them on their Discord. Here is the [Discord link](https://discord.com/invite/reQZEXu) and I hope you can figure it out and solve the problem.

(From: Another Valhelsia user)
