### ISSUE TITLE
Chemical X Advancement 

### ISSUE THREAD

**Issue by DaRocketeer15** [ValhelsiaTeam/Valhelsia#33]
When you brew any potion, it will give you the Chemical X advancement. Also, the spawning of their monsters are greatly reduced.

**Comment by Vaelzan** [comment]
The Chemical X advancement being triggered by brewing anything was a bug in Mutant Beasts that has been fixed in their latest release - they changed the criteria to actually having Chemical X in your inventory.

We have tweaked the spawn rates as they were spawning excessively in The Midnight dimension to the point of that dimension being essentially unplayable.

**Comment by Khytwel** [comment]
Mod deleted in the last version of the Valhelsia 2.

**Comment by FranciscoCHT** [comment]
Why was the mod deleted and not reduced the spawn rates only? It was a good mod 😢

**Comment by Vaelzan** [comment]
Because of bugs, including crashes. We were initially reporting them to the developer but it has become too difficult to keep supporting the mod given how frequently it has issues.
