### ISSUE TITLE
Sugar Cane not growing

### ISSUE THREAD

**Issue by Ekssam** [ValhelsiaTeam/Valhelsia#55]
Sugar cane harvested leaving 1 high. planted sugar cane around water. Hasn't grown at all in 14 game days. Installed Snad mod to see if that helped but no luck.

**Comment by Vaelzan** [comment]
This is intentional due to the Serene Seasons mod. You can get it to grow by placing glass above it to make a greenhouse. When the season changes it will grow quite quickly even without that though. If you dislike the behaviour of Serene Seasons it has a config option to disable the growth changes. You can also see the current season by crafting a calendar. Finally, using a botany pot to grow it will work too.
