### ISSUE TITLE
Crashes when joining the world :(

### ISSUE THREAD

**Issue by KidaCakes** [ValhelsiaTeam/Valhelsia#56]
Every time i try to make a new world with this modpack, it will get me all the way to the point of joining world. once i go anywhere near the screen or click the screen, it will crash. i have tried to make new worlds and i have left the computer for 10 minutes when it says joining world. However, none of it has had a chance to work. i have also shut down my computer, any suggestions on how i can fix this. Please help :(

**Comment by SuperCatGaming** [comment]
I seem to have a similar problem. Not completely sure, but it seems the issue, for me at least, is Bonsai trees. Currently testing that theory though. This is a crash happening after an update from 2.1.3 -> 2.2.1a

Crash report: https://pastebin.com/is9i0N9w

**Comment by SuperCatGaming** [comment]
Can confirm that removing Bonsai trees has resolved the issue for me.

**Comment by Vaelzan** [comment]
@SuperCatGaming Immersive Portals isn't in 2.2.1a, so you may have updated the pack with an unusual method unless you intentionally added it back. Regardless, it's a conflict between that mod and Bonsai Trees, which wouldn't happen with the base pack. Indeed, part of the reason it was removed from the pack was because of bugs like that.

**Comment by Vaelzan** [comment]
For the original issue, GitHub is not the place for support. Please see Discord if you are having trouble.
